from __future__ import annotations

import pathlib
import shutil
import subprocess
import tempfile
from typing import TYPE_CHECKING, Literal, Optional, Tuple

import pyarrow as pa
import pyarrow.compute as pc
from pyarrow import compute, csv

from khisto import KHISTO_BIN_DIR, logger

if TYPE_CHECKING:
    from khisto.typing import GranularityT


def _parse_file_type(
    file_path: pathlib.Path,
) -> Tuple[Literal["best_histogram", "histogram", "series"], Optional[int]]:
    """Determine the type of histogram file based on its name.

    Parameters
    ----------
    file_path : pathlib.Path
        Path to the histogram file.

    Returns
    -------
    tuple of (str, int or None)
        A tuple containing:
        - file_type : {'best_histogram', 'histogram', 'series'}
            Type of the histogram file.
        - histogram_id : int or None
            Histogram ID number for "histogram" type, None otherwise.

    Raises
    ------
    ValueError
        If the filename pattern is not recognized.
    """
    name = file_path.name

    if name == "histogram.csv":
        return "best_histogram", None
    if name == "histogram.series.csv":
        return "series", None

    # Check for histogram.(number).csv pattern
    stem = file_path.stem
    if stem.startswith("histogram.") and stem.split(".")[-1].isdigit():
        return "histogram", int(stem.split(".")[-1]) - 1

    raise ValueError(f"Unrecognized histogram file name: {name}")


def _process_histogram_files(
    temp_dir: str, base_name: str, only_best: bool
) -> pa.Table:
    """Process histogram files generated by khisto CLI.

    Parameters
    ----------
    temp_dir : str
        Directory containing histogram files.
    base_name : str
        Base name of histogram files (without extension).
    only_best : bool
        Whether only the best histogram was generated.

    Returns
    -------
    pa.Table
        Combined PyArrow Table with all histogram data.
    """
    # Column schema for histogram files
    HISTOGRAM_SCHEMA = {
        "LowerBound": pa.float64(),
        "UpperBound": pa.float64(),
        "Length": pa.float64(),
        "Frequency": pa.int64(),
        "Probability": pa.float64(),
        "Density": pa.float64(),
    }

    SERIES_SCHEMA = {
        "FileName": pa.string(),
        "Granularity": pa.int32(),
        "IntervalNumber": pa.int32(),
        "PeakIntervalNumber": pa.int32(),
        "SpikeIntervalNumber": pa.int32(),
        "EmptyIntervalNumber": pa.int32(),
        "Level": pa.float64(),
        "InformationRate": pa.float64(),
        "TruncationEpsilon": pa.float64(),
        "RemovedSingularityNumber": pa.int32(),
        "Raw": pa.bool_(),
    }

    histogram_data: list[pa.Table] = []
    histogram_series_df: Optional[pa.Table] = None

    # Read and process all histogram files
    for file in pathlib.Path(temp_dir).glob(f"{base_name}*"):
        ftype, hist_id = _parse_file_type(file)

        if ftype == "best_histogram" and only_best:
            data = csv.read_csv(
                file, convert_options=csv.ConvertOptions(column_types=HISTOGRAM_SCHEMA)
            )
            data = data.append_column(
                "granularity", pa.array([0] * len(data), type=pa.int32())
            ).append_column("is_best", pa.array([True] * len(data)))
            histogram_data.append(data)

        elif ftype == "histogram":
            data = csv.read_csv(
                file, convert_options=csv.ConvertOptions(column_types=HISTOGRAM_SCHEMA)
            )
            data = data.append_column(
                "granularity", pa.array([hist_id] * len(data), type=pa.int32())
            )
            histogram_data.append(data)

        elif ftype == "series":
            histogram_series_df = csv.read_csv(
                file, convert_options=csv.ConvertOptions(column_types=SERIES_SCHEMA)
            )

    # Combine all histogram tables
    histogram_df = pa.concat_tables(histogram_data)
    histogram_df = histogram_df.rename_columns(
        {
            "LowerBound": "lower_bound",
            "UpperBound": "upper_bound",
            "Length": "length",
            "Frequency": "frequency",
            "Probability": "probability",
            "Density": "density",
        }
    )

    # Mark the best histogram if series data is available
    if histogram_series_df is not None:
        # TODO: change the best selection criteria
        max_level = compute.max(histogram_series_df["Level"]).as_py()
        best_granularity = (
            histogram_series_df.filter(
                compute.equal(histogram_series_df["Level"], max_level)
            )["Granularity"][0].as_py()
            - 1
        )

        histogram_df = histogram_df.append_column(
            "is_best",
            compute.equal(histogram_df["granularity"], best_granularity),
        )

    histogram_df = histogram_df.append_column(
        "center",
        compute.divide(
            compute.add(histogram_df["lower_bound"], histogram_df["upper_bound"]),
            pa.scalar(2.0, type=pa.float64()),
        ),
    )

    return histogram_df


def compute_histogram(
    x: pa.Array, granularity: Optional[GranularityT] = None
) -> pa.Table:
    """Compute histogram of an array using khisto CLI.

    Parameters
    ----------
    x : pa.Array
        PyArrow Array of numeric values.
    granularity : int or 'best', optional
        Desired histogram granularity level.
        If None, all granularities are computed.
        If 'best', only the best histogram is computed.
        If an integer, the histogram with that granularity is returned.

    Returns
    -------
    pa.Table
        A PyArrow Table with histogram data including columns:
        - lower_bound : float64
            Lower bound of each bin.
        - upper_bound : float64
            Upper bound of each bin.
        - center : float64
            Center of each bin.
        - length : float64
            Length of each bin.
        - frequency : int64
            Frequency count in each bin.
        - probability : float64
            Probability of each bin.
        - density : float64
            Density of each bin.
        - granularity : int32
            Histogram granularity level.
        - is_best : bool
            Whether this is the best histogram.

    Raises
    ------
    subprocess.CalledProcessError
        If khisto CLI execution fails.
    ValueError
        If granularity is not specified correctly.
    TypeError
        If input array is not numeric.
    """
    if not pa.types.is_floating(x.type) and not pa.types.is_integer(x.type):
        raise TypeError(f"Array must be numeric, got {x.type}")

    # Create temporary input file with array values
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".txt", delete=False
    ) as temp_input:
        csv.write_csv(
            pa.Table.from_arrays([x], names=["value"]),
            temp_input.name,
            write_options=csv.WriteOptions(include_header=False),
        )
        temp_input_path = temp_input.name

    # Create temporary directory for output files
    temp_dir = tempfile.mkdtemp(prefix="khisto_output_")
    output_file = pathlib.Path(temp_dir) / "histogram.csv"
    cmd = []
    try:
        # Build command arguments
        cmd = [str(KHISTO_BIN_DIR), temp_input_path, str(output_file)]
        if granularity != "best":
            cmd.insert(1, "-e")  # Exploratory mode for all histograms

        # Execute khisto CLI
        subprocess.run(cmd, capture_output=True, text=True, check=True)

        df = _process_histogram_files(temp_dir, output_file.stem, granularity == "best")

        # Filter by specified granularity if needed. Takes the most granular if too high.
        if granularity != "best" and granularity is not None:
            max_granularity = pc.max(df["granularity"]).as_py()
            selected_granularity = min(granularity, max_granularity)
            df = df.filter(
                pc.equal(
                    df["granularity"], pa.scalar(selected_granularity, type=pa.int32())
                )
            )

        return df

    except subprocess.CalledProcessError as e:
        logger.error(f"Error executing khisto: {e.stderr} \n Command: {' '.join(cmd)}")
        raise
    finally:
        # Clean up temporary input file and directory
        pathlib.Path(temp_input_path).unlink(missing_ok=True)
        shutil.rmtree(temp_dir, ignore_errors=True)
