"""Core module for computing optimal histograms using the khisto CLI.

This module provides the interface to the khisto binary for computing
optimal histograms using the Khiops algorithm.
"""

from __future__ import annotations

import csv
import pathlib
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from typing import Optional, Tuple, Literal, overload

import numpy as np
from numpy.typing import NDArray

from khisto import KHISTO_BIN_DIR, logger


@dataclass
class HistogramResult:
    """Result of optimal histogram computation.

    Attributes
    ----------
    lower_bound : NDArray[np.float64]
        Lower bounds of each bin.
    upper_bound : NDArray[np.float64]
        Upper bounds of each bin.
    frequency : NDArray[np.int64]
        Count of values in each bin.
    probability : NDArray[np.float64]
        Probability of each bin (frequency / total).
    density : NDArray[np.float64]
        Density of each bin (probability / bin_width).
    is_best : bool
        Whether this histogram is the optimal one.
    granularity : int
        The granularity level of this histogram.
    """

    lower_bound: NDArray[np.float64]
    upper_bound: NDArray[np.float64]
    frequency: NDArray[np.int64]
    probability: NDArray[np.float64]
    density: NDArray[np.float64]
    is_best: bool = False
    granularity: int = 0

    @property
    def bin_edges(self) -> NDArray[np.float64]:
        """Return bin edges array (n_bins + 1 values)."""
        return np.concatenate([self.lower_bound, [self.upper_bound[-1]]])

    @property
    def bin_widths(self) -> NDArray[np.float64]:
        """Return width of each bin."""
        return self.upper_bound - self.lower_bound

    @property
    def bin_centers(self) -> NDArray[np.float64]:
        """Return center of each bin."""
        return (self.lower_bound + self.upper_bound) / 2

    def __len__(self) -> int:
        """Return number of bins."""
        return len(self.lower_bound)


def _parse_file_type(
    file_path: pathlib.Path,
) -> Tuple[Literal["best_histogram", "histogram", "series"], Optional[int]]:
    """Determine the type of histogram file based on its name.

    Parameters
    ----------
    file_path : pathlib.Path
        Path to the histogram file.

    Returns
    -------
    tuple of (str, int or None)
        A tuple containing:
        - file_type : {'best_histogram', 'histogram', 'series'}
            Type of the histogram file.
        - histogram_id : int or None
            Histogram ID number for "histogram" type, None otherwise.

    Raises
    ------
    ValueError
        If the filename pattern is not recognized.
    """
    name = file_path.name

    if name == "histogram.csv":
        return "best_histogram", None
    if name == "histogram.series.csv":
        return "series", None

    # Check for histogram.(number).csv pattern
    stem = file_path.stem
    if stem.startswith("histogram.") and stem.split(".")[-1].isdigit():
        return "histogram", int(stem.split(".")[-1]) - 1

    raise ValueError(f"Unrecognized histogram file name: {name}")


def _read_csv_to_arrays(file_path: pathlib.Path) -> dict[str, np.ndarray]:
    """Read CSV file into dictionary of numpy arrays.

    Parameters
    ----------
    file_path : pathlib.Path
        Path to CSV file.

    Returns
    -------
    dict[str, np.ndarray]
        Dictionary mapping column names to numpy arrays.
    """
    with open(file_path, "r", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if not rows:
        return {}

    result = {}
    columns = rows[0].keys()

    for col in columns:
        values = [row[col] for row in rows]
        # Try to convert to appropriate numeric type
        try:
            # Try int first
            result[col] = np.array([int(v) for v in values], dtype=np.int64)
        except ValueError:
            try:
                # Try float
                result[col] = np.array([float(v) for v in values], dtype=np.float64)
            except ValueError:
                # Keep as string
                result[col] = np.array(values, dtype=object)

    return result


def _process_histogram_files(
    temp_dir: str,
    base_name: str,
    only_best: bool,
    max_bins: Optional[int],
    return_all: bool = False,
) -> HistogramResult | list[HistogramResult]:
    """Process histogram files generated by khisto CLI.

    Parameters
    ----------
    temp_dir : str
        Directory containing histogram files.
    base_name : str
        Base name of histogram files (without extension).
    only_best : bool
        Whether only the best histogram was generated.
    max_bins : int or None
        Maximum number of bins. If None, use the best histogram.
    return_all : bool, default False
        If True, return all histograms as a list with is_best marked.

    Returns
    -------
    HistogramResult or list[HistogramResult]
        Structured result(s) with histogram data.
    """
    histogram_data: list[tuple[int, dict[str, np.ndarray]]] = []
    series_data: Optional[dict[str, np.ndarray]] = None

    # Read and process all histogram files
    for file in pathlib.Path(temp_dir).glob(f"{base_name}*"):
        ftype, hist_id = _parse_file_type(file)

        if ftype == "best_histogram" and only_best:
            data = _read_csv_to_arrays(file)
            return HistogramResult(
                lower_bound=data["LowerBound"].astype(np.float64),
                upper_bound=data["UpperBound"].astype(np.float64),
                frequency=data["Frequency"].astype(np.int64),
                probability=data["Probability"].astype(np.float64),
                density=data["Density"].astype(np.float64),
                is_best=True,
                granularity=0,
            )

        elif ftype == "histogram":
            data = _read_csv_to_arrays(file)
            assert hist_id is not None  # histogram type always has an id
            histogram_data.append((hist_id, data))

        elif ftype == "series":
            series_data = _read_csv_to_arrays(file)

    # Sort by granularity
    histogram_data.sort(key=lambda x: x[0])

    if not histogram_data:
        raise ValueError("No histogram data found")

    # Determine best granularity
    best_granularity: Optional[int] = None
    if series_data is not None:
        max_level_idx = int(np.argmax(series_data["Level"]))
        best_granularity = int(series_data["Granularity"][max_level_idx]) - 1

    # Return all histograms if requested
    if return_all:
        results = []
        for granularity, data in histogram_data:
            is_best = (
                granularity == best_granularity
                if best_granularity is not None
                else False
            )
            results.append(
                HistogramResult(
                    lower_bound=data["LowerBound"].astype(np.float64),
                    upper_bound=data["UpperBound"].astype(np.float64),
                    frequency=data["Frequency"].astype(np.int64),
                    probability=data["Probability"].astype(np.float64),
                    density=data["Density"].astype(np.float64),
                    is_best=is_best,
                    granularity=granularity,
                )
            )
        return results

    # Find best granularity from series data or use max_bins constraint
    if max_bins is not None:
        # Find the granularity that respects max_bins
        selected_data = None
        selected_granularity = 0
        for granularity, data in histogram_data:
            n_bins = len(data["LowerBound"])
            if n_bins <= max_bins:
                selected_data = data
                selected_granularity = granularity
            else:
                break
        # If no histogram respects the constraint, use the coarsest one
        if selected_data is None and histogram_data:
            selected_data = histogram_data[0][1]
            selected_granularity = histogram_data[0][0]
    elif best_granularity is not None:
        # Find matching histogram
        selected_data = None
        selected_granularity = best_granularity
        for granularity, data in histogram_data:
            if granularity == best_granularity:
                selected_data = data
                break
        if selected_data is None and histogram_data:
            selected_data = histogram_data[-1][1]
            selected_granularity = histogram_data[-1][0]
    else:
        # Default to finest granularity
        selected_data = histogram_data[-1][1]
        selected_granularity = histogram_data[-1][0]

    if selected_data is None:
        raise ValueError("No histogram data found")

    is_best = (
        selected_granularity == best_granularity
        if best_granularity is not None
        else True
    )

    return HistogramResult(
        lower_bound=selected_data["LowerBound"].astype(np.float64),
        upper_bound=selected_data["UpperBound"].astype(np.float64),
        frequency=selected_data["Frequency"].astype(np.int64),
        probability=selected_data["Probability"].astype(np.float64),
        density=selected_data["Density"].astype(np.float64),
        is_best=is_best,
        granularity=selected_granularity,
    )


@overload
def compute_histogram(
    x: np.ndarray,
    max_bins: Optional[int] = ...,
    range: Optional[tuple[float, float]] = ...,
    *,
    return_all: Literal[False] = ...,
) -> HistogramResult: ...


@overload
def compute_histogram(
    x: np.ndarray,
    max_bins: Optional[int] = ...,
    range: Optional[tuple[float, float]] = ...,
    *,
    return_all: Literal[True],
) -> list[HistogramResult]: ...


def compute_histogram(
    x: np.ndarray,
    max_bins: Optional[int] = None,
    range: Optional[tuple[float, float]] = None,
    return_all: bool = False,
) -> HistogramResult | list[HistogramResult]:
    """Compute optimal histogram of an array using khisto CLI.

    Parameters
    ----------
    x : np.ndarray
        Array of numeric values.
    max_bins : int, optional
        Maximum number of bins. If None, the algorithm selects the optimal number.
    range : tuple of (float, float), optional
        The lower and upper range of the bins. If not provided, range is
        (x.min(), x.max()). Values outside the range are ignored.
    return_all : bool, default False
        If True, return all histograms at different granularity levels.
        Each histogram will have `is_best` set to indicate the optimal one.

    Returns
    -------
    HistogramResult or list[HistogramResult]
        If return_all is False: a single HistogramResult containing:
        - lower_bound : array of lower bin bounds
        - upper_bound : array of upper bin bounds
        - frequency : count in each bin
        - probability : probability of each bin
        - density : density of each bin
        - is_best : whether this is the optimal histogram
        - granularity : the granularity level

        If return_all is True: a list of HistogramResult, one per granularity,
        sorted from coarsest to finest.

    Raises
    ------
    subprocess.CalledProcessError
        If khisto CLI execution fails.
    TypeError
        If input array is not numeric.
    ValueError
        If input array is empty after filtering.
    """
    # Convert to numpy array if needed
    x = np.asarray(x, dtype=np.float64)

    # Filter by range if specified
    if range is not None:
        min_val, max_val = range
        mask = (x >= min_val) & (x <= max_val)
        x = x[mask]

    # Remove NaN values
    x = x[~np.isnan(x)]

    if len(x) == 0:
        raise ValueError("Input array is empty after filtering")

    # Create temporary input file with array values
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".txt", delete=False
    ) as temp_input:
        for val in x:
            temp_input.write(f"{val}\n")
        temp_input_path = temp_input.name

    # Create temporary directory for output files
    temp_dir = tempfile.mkdtemp(prefix="khisto_output_")
    output_file = pathlib.Path(temp_dir) / "histogram.csv"
    cmd = []

    try:
        # Build command arguments
        cmd = [str(KHISTO_BIN_DIR), temp_input_path, str(output_file)]

        # Use exploratory mode if we need all histograms or constrained histogram
        use_exploratory = max_bins is not None or return_all
        if use_exploratory:
            cmd.insert(1, "-e")  # Exploratory mode for all histograms

        # Execute khisto CLI
        subprocess.run(cmd, capture_output=True, text=True, check=True)

        result = _process_histogram_files(
            temp_dir,
            output_file.stem,
            only_best=not use_exploratory,
            max_bins=max_bins,
            return_all=return_all,
        )

        return result

    except subprocess.CalledProcessError as e:
        logger.error(f"Error executing khisto: {e.stderr} \n Command: {' '.join(cmd)}")
        raise
    finally:
        # Clean up temporary input file and directory
        pathlib.Path(temp_input_path).unlink(missing_ok=True)
        shutil.rmtree(temp_dir, ignore_errors=True)
